Basic containers network support
bazhenov/docker-testng-integration pull request #13
Opened 2021-08-19 08:34 UTC by yargray

Basic support for creation user defined networks between containers with network aliases

2021-08-23 04:32 UTC, bazhenov commented
@yargray добавь пожалуйста описание фичи в README.md, чтобы у нас доки как-то "намекали" что такой функционал имеется.

2021-08-23 04:33 UTC, bazhenov commented on src/main/java/me/bazhenov/docker/Container.java
> +	String networkAlias() default "";
Я только что узнал о наличии `--network-alias` у `docker run` :)

2021-08-24 00:05 UTC, bazhenov requested changes

2021-08-24 03:28 UTC, yargray commented on src/main/java/me/bazhenov/docker/Docker.java
> +		synchronized (networks) {
Возможна ситуация когда close() и createNetwork() могут быть вызваны одновременно из разных потоков, тогда будет попытка кильнуть еще несозданную сеть, либо потеря ссылки на созданную сеть, что окончится либо падением close(), либо осиротевшей сетью в докере. Синхронизация должна избавить от подобной проблемы.

2021-08-24 05:43 UTC, yargray commented
> @yargray добавь пожалуйста описание фичи в README.md, чтобы у нас доки как-то "намекали" что такой функционал имеется.

Добавил пример в ридми

2021-08-30 00:43 UTC, bazhenov approved these changes

2021-08-30 00:45 UTC, merged